name: Deploy Back-Office

on:
  push:
    branches:
      - main
    paths:
      - "back-office/**"
      - ".github/workflows/back-office-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CDF_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      VITE_CORE_API_URL: http://localhost:3000/admins
      VITE_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      VITE_GOOGLE_REDIRECT_URL: ${{ secrets.GOOGLE_REDIRECT_URL }}
    defaults:
      run:
        working-directory: ./back-office

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: back-office/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront
        if: env.CDF_ID != ''
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CDF_ID }} --paths "/*"
